server.port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/facultate?currentSchema=APBDOO
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: validate